data<-read.csv("household_power_consumption.txt",sep=";")
data2<-subset(data,as.Date(strptime(data$Date,"%d/%m/%Y"))=="2007-02-01" |as.Date(strptime(data$Date,"%d/%m/%Y"))=="2007-02-02")
png("plot1.png",width = 480,height = 480)
hist(as.numeric(data2$Global_active_power),main="Global Active Power",col="red",xlab="Global Active Powers (kilowatts)")
dev.off()
